useViper: false
httpSrvPort: 8080
hobbies:
- skateboarding
- snowboarding
- go
mysql:
  URL: root:11111111@tcp(localhost:3306)
  dbName: myconsult
  idle: 256
  maxOpen: 1024
  debug: true
LogMode: 35
eyes : brown
beard: true