useViper: true
httpSrvPort: 8080
debugLevel: info  #DEBUG INFO WARN ERROR OFF
mysql:
  URL: root:11111111@tcp(localhost:3306)
  dbName: ethsmart
  idle: 256
  maxOpen: 1024
  debug: false
nsq:
  nodeAddress: 127.0.0.1:4151
  maxInFlight: 100
  lookupsAddress: 127.0.0.1:4161
  debug: true
common:
  debug: true
ethereum:
  endpoints: 
    - http://18.222.179.249:21024
    - http://18.222.179.249:21024
  adminaccount: 0x1dcef12e93b0abf2d36f723e8b59cc762775d513
  gas: 100000  # 10万
  price: 30000000000  # 30GWei
  debug: true
poa:
  endpoints: 
    - http://18.222.179.249:21024
    - http://18.222.179.249:21024
solidity:
  source:
    - ERC20/TokenTimelock
    - ERC20/TokenVesting
  exclude:
    ERC20,ERC20Basic,SafeERC20,SafeMath,Ownable
hdwallet:
  stored: ./.___000data000__