useViper: true
httpSrvPort: 8080
debugLevel: debug  #DEBUG INFO WARN ERROR OFF
mysql:
  URL: root:11111111@tcp(localhost:3306)
  dbName: myconsult
  idle: 256
  maxOpen: 1024
  debug: true
nsq:
  nodeAddress: 127.0.0.1:4151
  maxInFlight: 100
  lookupsAddress: 127.0.0.1:4161
  debug: true
common:
  debug: true
ethereum:
  endpoints: 
    - http://18.222.179.249:21024
    - http://18.222.179.249:21024
  debug: true
poa:
  endpoints: 
    - http://18.222.179.249:21024
    - http://18.222.179.249:21024
solidity:
  source:
    - ERC20/TokenTimelock
    - ERC20/TokenVesting
  exclude:
    ERC20,ERC20Basic,SafeERC20,SafeMath,Ownable
hdwallet:
  stored: ./.___000data000__