useViper: true
httpSrvPort: 8080
debugLevel: info  #DEBUG INFO WARN ERROR OFF
mysql:
  URL: root:11111111@tcp(localhost:3306)
  dbName: ethsmart
  idle: 256
  maxOpen: 1024
  debug: false
nsq:
  nodeAddress: 127.0.0.1:4151
  maxInFlight: 100
  lookupsAddress: 127.0.0.1:4161
  debug: true
common:
  verifycodetimeout: 600
  debug: true
ethereum:
  endpoints: 
    - http://18.222.179.249:21024
    - http://18.222.179.249:21024
  adminaccount: 0x1dcef12e93b0abf2d36f723e8b59cc762775d513
  omcaddress: 0x33745820325d0415eDA3d027d4e020454c43108e
  gas: 100000  # 10万
  price: 30000000000  # 30GWei
  txtimeout: 600  #10分钟
  txcomfired: 12  #交易确认块数
  debug: true
poa:
  endpoints: 
    - http://18.222.179.249:21024
    - http://18.222.179.249:21024
  pointsaddress: 0x04695Fb0d138876f25dAF98d11e9b7206d90721e
  txtimeout: 120  #120秒
  txcomfired: 3  #交易确认块数
solidity:
  source:
    - ERC20/OMC  
    - ERC20/PointCoin
  exclude:
    ERC20,ERC20Basic,SafeERC20,SafeMath,Ownable,BasicToken,BurnableToken,DetailedERC20,StandardToken,StandardBurnableToken,MintableToken
hdwallet:
  stored: ./.___000data000__